FROM python:3.10

WORKDIR /code

RUN pip install fastapi uvicorn openai python-dotenv

COPY ./chatbot.py /code/
COPY ./.env /code/

# docker run 을 하면 기본으로 실행하는 명령. 빌드하고 실행한다는 것이 아님
CMD ["uvicorn", "chatbot:app", "--host", "0.0.0.0", "--port", "8002"]
