FROM python:3.10

WORKDIR /code

RUN pip install fastapi uvicorn python-multipart openai python-dotenv

COPY ./asr.py /code/
COPY ./.env /code/

CMD ["uvicorn", "asr:app", "--host", "0.0.0.0", "--port", "8001"]
