FROM python:3.10

WORKDIR /code

RUN apt update
RUN apt install ffmpeg -y

RUN pip install fastapi uvicorn numpy pydub requests scipy python-multipart websockets

COPY ./main.py /code/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
