FROM python:3.10

WORKDIR /code

RUN pip install fastapi uvicorn openai python-dotenv

COPY ./chatbot.py /code/
COPY ./.env /code/

CMD ["uvicorn", "chatbot:app", "--host", "0.0.0.0", "--port", "8002"]
